# Generated by Django 5.1.1 on 2024-10-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profie_img',
            new_name='profile_img',
        ),
    ]
