# Generated by Django 5.1.1 on 2024-10-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('CSD', 'CSD'), ('AIML', 'AIML'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE')], max_length=50),
        ),
    ]
