# Generated by Django 5.1.1 on 2024-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('CSD', 'CSD'), ('AIML', 'AIML'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE')], default='CSE', max_length=50),
        ),
    ]
