# Generated by Django 5.1.1 on 2024-10-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_branch_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('CSD', 'CSD'), ('AIML', 'AIML'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE')], default='', max_length=50),
        ),
    ]
